In [1]:
a=5#int
b=True#bool
c=3.14#float
d="apple"#string


In [18]:
a=10

In [3]:
print(a)

10


In [8]:
a=5.25

In [9]:
print(a)

5.25


In [29]:
print(type(str(a)))

<class 'str'>


In [17]:
print('hello world')

hello world


In [27]:
'''
hello apple
hello 10
'''
print("hello "+d)
print("hello",a)
print("hello "+str(a))

hello apple
hello 10
hello 10


In [35]:
n=5
ans=int(str(n)*3)+int(str(n)*2)+n
print(ans)

615


In [30]:
666+66+6

738

In [31]:
555+55+5

615

In [33]:
5*111+5*11+5

615

In [52]:
n=float(input("Enter the value for n :"))
name=input("enter your name :")

Enter the value for n :3.3
enter your name :hi


In [41]:
print(n)

15


In [42]:
type(n)

int

In [46]:
print("user %s entered the value %d for n"%(name,n))

user mango entered the value 20 for n


In [ ]:
area of circle,rectangle,triangle

The area of the circle is 25 sq.cm

In [50]:
int(3.3)

3

In [49]:
float(3)

3.0

In [55]:
int("3")


3

In [54]:
float('3.3')

3.3

In [ ]:
+ - * / % 
and or not  
> < <= >= == != 

a,b
a=b
a<=b
a>=b
a<b
a>b


In [56]:
b=5
a=b

In [57]:
a

5

In [1]:
n=int(input("Enter the value for n :"))
if n%2==0:
    print("Even")
else:
    print("odd")

Enter the value for n :10
Even


In [5]:
n=int(input("Enter the value for n :"))
if n%4==0:
    print("divisible by 4 and Even")
elif n%2==0:
    print("even")
else:
    print("odd")

Enter the value for n :5
odd


In [ ]:
opt-> circle,rectangle,triangle


In [14]:
count=0
opt='y'
while opt=='y':
    n=int(input("Enter the value for n :"))
    if n==15:
        print("Goodbye!!!")
        break
    elif n==25:
        print("skipping...")
        continue
    elif n==20:
        count+=1
        pass
    if n%4==0:
        print("divisible by 4 and Even")
    elif n%2==0:
        print("even")
    else:
        print("odd")
    opt=input("Do you want to continue? y/n")
print("The number 20 is repeated for %d"%count)

Enter the value for n :78
even
Do you want to continue? y/ny
Enter the value for n :33
odd
Do you want to continue? y/nn
The number 20 is repeated for 0


## Rock-Paper-Scissor game

rock beats scissor

paper beats rock

scissor beats paper

In [24]:
while 1:
    user1=input("user1 :")
    user2=input("user2 :")
    if user1=="q" or user2=="q":
        print("good bye")
        break
    if (user1 =="rock" and user2=="scissor"):
        print("user1 won the game")
    elif (user1 =="paper" and user2=="rock"):
        print("user1 won the game")
    elif (user1 =="scissor" and user2=="paper"):
        print("user1 won the game")
    elif user1 ==user2:
        print("game is tie")
    else:
        print("user2 won the game")

user1 :paper
user2 :q
good bye


In [25]:
import random as r
comp=r.randint(0,50)

In [31]:
r.randint(0,50)

46

In [56]:
name="elephaNT"

In [48]:
name[2:6:1]

'epha'

In [41]:
len(name)

8

In [51]:
name[-5:-1]

'phan'

In [52]:
name[::-1]

'tnahpele'

In [54]:
print(name.capitalize())

Elephant


In [60]:
name.casefold()
name.swapcase()


'elephaNT'

In [64]:
name.count('e')

2

In [67]:
name.encode()


b'elephaNT'

In [69]:
print(name.endswith('NT'))
print(name.startswith('e'))

True
True


In [70]:
name.lower()

'elephant'

In [71]:
name.upper()

'ELEPHANT'

In [84]:
name.index('h')
#name.replace("NT","nt")
n=' '

In [86]:
name.isalpha()
name.isalnum()
n.isdigit()
n.isspace()
name.islower()
name.isupper()

False

In [87]:
name=" apple "

In [88]:
name.rstrip()

' apple'

In [89]:
name.lstrip()

'apple '

In [90]:
name.strip()

'apple'

In [91]:
name="elephant is a big animal"

In [94]:
d=name.split('a')

In [100]:
'a'.join(name.split('a'))

'elephant is a big animal'

In [96]:
d

['eleph', 'nt is ', ' big ', 'nim', 'l']

Elephant is an animal . --> . animal an is Elephant <br>
palindrome

In [102]:
stmt="Elephant is an animal ."

In [105]:
print(' '.join(stmt.split()[::-1]))

. animal an is Elephant


In [108]:
' '.join(stmt.split()[::-1])

'. animal an is Elephant'

In [109]:
name="madam"
nam="apple"

In [111]:
if nam==nam[::-1]:
    print("yes")

In [114]:
L=[]
l=[1,2,3,4,'apple','ball','cat','a','b','c']

In [120]:
a=l[::-1]

In [122]:
l.reverse()

In [121]:
a

['c', 'b', 'a', 'cat', 'ball', 'apple', 4, 3, 2, 1]

In [123]:
l

['c', 'b', 'a', 'cat', 'ball', 'apple', 4, 3, 2, 1]

In [128]:
l.append("dog")

In [130]:
l.pop()

'dog'

In [131]:
l

['c', 'b', 'a', 'cat', 'ball', 'apple', 4, 3, 2, 1, 'dog']

In [132]:
l.index('cat')

3

In [133]:
l.insert(3,"bat")

In [134]:
l

['c', 'b', 'a', 'bat', 'cat', 'ball', 'apple', 4, 3, 2, 1, 'dog']

In [135]:
l.remove('ball')

In [136]:
l

['c', 'b', 'a', 'bat', 'cat', 'apple', 4, 3, 2, 1, 'dog']

In [137]:
l.index(2)

8

In [139]:
l[8]="a"

In [140]:
l

['c', 'b', 'a', 'bat', 'cat', 'apple', 4, 3, 'a', 1, 'dog']

In [141]:
del l[9]

In [142]:
l

['c', 'b', 'a', 'bat', 'cat', 'apple', 4, 3, 'a', 'dog']

In [143]:
l.count('a')

2

In [144]:
l.sort()

TypeError: '<' not supported between instances of 'int' and 'str'

In [150]:
l.extend(["elephant","mango"])

In [148]:
l.pop()

['elephant', 'mango']

In [151]:
l

['a', 'apple', 'b', 'bat', 'c', 'cat', 4, 3, 'a', 'dog', 'elephant', 'mango']

In [152]:
import random as r
comp=r.randint(100,999)

In [15]:
t=('c', 'b', 'a', 'bat', 'cat', 'apple', 4, 3, 'a', 'dog')
l=['c', 'b', 'a', 'bat', 'cat', 'apple', 4, 3, 'a', 'dog']
#tuple

In [3]:
t[2:6]

('a', 'bat', 'cat', 'apple')

In [5]:
t[3]="ball"

TypeError: 'tuple' object does not support item assignment

In [6]:
del t[3]

TypeError: 'tuple' object doesn't support item deletion

In [14]:
name="apple"
for i in range(5):
    print(name[i])

a
p
p
l
e


In [13]:
len(name)

5

In [22]:
for j in range(len(l)):
    print(j)
    print(l[j])

0
c
1
b
2
a
3
bat
4
cat
5
apple
6
4
7
3
8
a
9
dog


In [23]:
for k in l[2:7]:
    print(k)

a
bat
cat
apple
4


take two numerical list of variable length and print the common numbers without duplicated in those lists in a single line <Br>
take a numerical list and return new list with the value less than 9 from the first list

In [25]:
t=(1,2,3,4,5)
for j in t:
    print(t[j])

2
3
4
5


IndexError: tuple index out of range

In [32]:
a=[2,3,4,5,6,7,7,10,11,12,14]
b=[5,6,7,13,14,14]

In [37]:
c=[]
for bi in b:
    for ai in a:
        if ai==bi:
            if bi not in c:
                c.append(bi)

In [38]:
c

[5, 6, 7, 14]

In [39]:
c=[]
for I in b:
    if I in a and I not in c:
            c.append(I)
        

In [40]:
c

[5, 6, 7, 14]

In [44]:
d=[K for K in b if K <9]

In [45]:
d

[5, 6, 7]

In [47]:
list(set(a)&set(b))

[14, 5, 6, 7]

In [ ]:
https://www.w3resource.com/python-exercises/

In [ ]:
https://github.com/sharmasaravanan/Machine_learning

In [52]:
#dictionary
d={'name':["sharma"],"age":25,"organization":"Agentz","raja":"12/10/90"}

In [62]:
d['name']

'sharma'

In [72]:
name=input()
dob=input()
d[name]=dob


KeyboardInterrupt: 

In [73]:
d

{'name': 'sharma',
 'age': 25,
 'organization': 'Agentz',
 'mobile': 7418490015,
 'raja': '12/10/90',
 'john': '01/01/01'}

In [65]:
for key in d.keys():
    print(key)

name
age
organization
mobile


In [67]:
for value in d.values():
    print(value)
for item in d.items():
    print(item)

sharma
25
Agentz
7418490015
('name', 'sharma')
('age', 25)
('organization', 'Agentz')
('mobile', 7418490015)


In [68]:
for k,v in d.items():
    print(k,':',v)

name : sharma
age : 25
organization : Agentz
mobile : 7418490015


In [ ]:
populate the dictionary 

option -> add/display

a-> display
    input-> name 
    output -> john's date of birth is 1/1/01
    
b-> add
    input-> name , DOB
    operation -> adding in dictionary
    output -> xxx's DOB details has been added into a dict 


In [39]:
#error handling
#function
try:
    print(v)
except NameError, e:
    print("There is some error!!!")
    print(e)
finally:
    a=10
    print("Displaying default a value:- a",a)

SyntaxError: invalid syntax (<ipython-input-39-4ed34c0368e4>, line 5)

In [40]:
print(a)
print(5+10)

cat
15


In [15]:
a="cat"

In [16]:
try:
    int(a)
except:
    ''

ValueError: invalid literal for int() with base 10: 'cat'

In [37]:
def add(a,b=25):
    return(a+b,a*b)

In [35]:
c=int(input("a :"))
d=int(input("b :"))
s,m=add(c,d)

a :6
b :5


In [36]:
s

16

In [33]:
m

30

In [41]:
a&b -> range ->10,20 25,45

SyntaxError: invalid syntax (<ipython-input-41-7491540e5b62>, line 1)

In [5]:
#math,random
#pip install <lib name>
import math as m
from random import randint,sample,choice

In [2]:
math.factorial(5)

120

In [4]:
m.factorial(5)

120

In [7]:
randint(0,50)

12

In [8]:
a=['rock','paper','scissor']

In [10]:
comp=choice(a)

'rock'

In [12]:
sample('scissor',2)

['r', 'c']

1. Password generator
2. hangman game

In [17]:
s="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~"

In [20]:
print(sample(s,8))

['/', '9', ';', 'F', 'W', '+', '_', 'H']


In [26]:
print("".join(sample(s,8)))

+d_Pf<k0


In [27]:
word="apple"


In [28]:
list(word)

['a', 'p', 'p', 'l', 'e']

In [30]:
list(len(word)*'_')

['_', '_', '_', '_', '_']

In [33]:
letter='p'
for i,ch in enumerate(word):
    if ch==letter:
        print(i)

1
2


In [34]:
#pip install numpy  -> cmd 
import numpy as np

In [35]:
a=[2,3,4,5,8,9,0,3,1]

In [37]:
a=np.reshape(a,[3,3])

In [39]:
print(a)

[[2 3 4]
 [5 8 9]
 [0 3 1]]


In [46]:
r,c=(2,1)

In [44]:
a[r]

array([5, 8, 9])

In [45]:
a[:,c]

array([4, 9, 1])

In [50]:
a[r][c]=15

In [51]:
a

array([[ 2,  3,  4],
       [ 5,  8,  9],
       [ 0, 15,  1]])

In [ ]:
#file handling
txt
csv
tsv
json
yml
xml
xlsx
db

In [16]:
txtfile = open("./brass.txt","a")
txtfile.write("hey\n")
txtfile.write("how do you do?\n")
txtfile.write("I am good\n")
txtfile.close()

In [21]:
txtfile = open("./brass.txt","r")


In [22]:
print(txtfile.readlines())

['Hello\n', 'how are you?\n', 'I am fine\n', 'hey\n', 'how do you do?\n', 'I am good\n']


In [24]:
txtfile.readlines?

In [2]:
#csv,tsv,xlsx
import pandas as pd

In [5]:
csvData = pd.read_csv("./fruits_vege.csv",index_col=0)

In [7]:
csvData['fruit']

a     apple
b     mango
c    orange
Name: fruit, dtype: object

In [10]:
csvData1 = pd.read_csv("./Advertising.csv",index_col=0)

In [13]:
csvData1.head(3)

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3

In [14]:
csvData1.describe()

TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [34]:
tsvData = pd.read_csv("./fruits_vege.tsv",delimiter="\t",index_col=0,header=0)

In [35]:
tsvData

fruit vegetable    fruits 2 vegetable 2
a   apple     onion       apple       onion
b   mango    potato       mango      potato
c  orange     beans  pine apple      carrot

In [21]:
tsvData[c]

KeyError: 'c'

In [28]:
tsvData.loc[:,0]

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [0] of <class 'int'>

In [39]:
tsvData.iloc[1,1]

'potato'

In [40]:
tsvData.iloc[:,2]

a         apple
b         mango
c    pine apple
Name: fruits 2, dtype: object

In [41]:
tsvData

fruit vegetable    fruits 2 vegetable 2
a   apple     onion       apple       onion
b   mango    potato       mango      potato
c  orange     beans  pine apple      carrot

In [43]:
xlData = pd.read_excel("./Course Syllabus.xlsx")

In [44]:
xlData

Syllabus    Duration
0     Introduction to Python      40 mins
1        Environment creation     20 mins
2    variables and expression     45 mins
3            conditional code     90 mins
4                   fucntions    120 mins
5         loops and iteration     90 mins
6                        List     45 mins
7                      Tuples     45 mins
8             Data Dictionary     45 mins
9               File handling    150 mins
10          importing library     40 mins
11           random libraries     90 mins
12        Sorting, Formatting     45 mins
13                 Statistics     45 mins
14   basics of flask & django     90 mins
15  arrays and graph plotting     90 mins
16            Sample Projects  120 mins\n
17                Total Hours    20 hours

In [45]:
excel = pd.ExcelFile("./Course Syllabus.xlsx")

In [46]:
excel

In [47]:
excel.sheet_names

['Basic Python',
 'Advanced Python',
 'Datascience with Python',
 'Machine Learning',
 'Deep Learning']

In [48]:
excelData = pd.read_excel(excel,sheet_name='Datascience with Python')

In [52]:
excelData.dropna(inplace=True)

In [53]:
excelData

Syllabus   Duration
0                     Basic Python   18 hours
1        The Series Data Structure  1.5 hours
2                Querying a Series  1.5 hours
3     The DataFrame Data Structure  1.5 hours
4   DataFrame Indexing and Loading  1.5 hours
5             Querying a DataFrame  1.5 hours
6              Indexing Dataframes  1.5 hours
7                   Missing Values  1.5 hours
8               Merging Dataframes  1.5 hours
9                    Pandas Idioms  1.5 hours
10                        Group by  1.5 hours
11                          Scales  1.5 hours
12                    Pivot Tables  1.5 hours
13              Date Functionality  1.5 hours
14                  Goodhart's Law  0.5 hours
15                   Distributions  1.5 hours
16              More Distributions  1.5 hours
17    Hypothesis Testing in Python  1.5 hours
18                  Sample Project    3 hours
20                     Total Hours   46 hours

In [54]:
df = dict()

In [56]:
df["states"]=["Tamil Nadu","Kerala","Andhra pradesh","Karnataka"]


In [57]:
df["language"]=["Tamil","Malayalam","Telugu","Kannada"]

In [62]:
df

{'states': ['Tamil Nadu', 'Kerala', 'Andhra pradesh', 'Karnataka'],
 'language': ['Tamil', 'Malayalam', 'Telugu', 'Kannada']}

In [60]:
DF = pd.DataFrame(df,index=['TN',"KL","AP","KA"])

In [67]:
DF.to_csv("./brass_tsv.tsv",sep="\t")

In [70]:
pd.read_csv("./brass_tsv.tsv",index_col=0,delimiter="\t")

states   language
TN      Tamil Nadu      Tamil
KL          Kerala  Malayalam
AP  Andhra pradesh     Telugu
KA       Karnataka    Kannada

In [71]:
DF.to_excel("./brass.xlsx")

In [72]:
DF.to_dict()

{'states': {'TN': 'Tamil Nadu',
  'KL': 'Kerala',
  'AP': 'Andhra pradesh',
  'KA': 'Karnataka'},
 'language': {'TN': 'Tamil',
  'KL': 'Malayalam',
  'AP': 'Telugu',
  'KA': 'Kannada'}}

In [73]:
DF.to_json()

'{"states":{"TN":"Tamil Nadu","KL":"Kerala","AP":"Andhra pradesh","KA":"Karnataka"},"language":{"TN":"Tamil","KL":"Malayalam","AP":"Telugu","KA":"Kannada"}}'

In [74]:
import json

In [75]:
jsonData = json.load(open("./test.json"))

In [76]:
jsonData

{'domainId': 'DOMAIN-100',
 'question': 'I want to book appointment',
 'language': 'EN_US',
 'type': 'TASK'}

In [77]:
jsonData['language']

'EN_US'

In [78]:
import yaml

In [79]:
ymlData = yaml.load(open("./config_sample.yml"))

In [80]:
ymlData

{'language': 'en',
 'pipeline': 'spacy_sklearn',
 'data': [True, 'yep', 'bye', 'goodbye', False]}

In [2]:
import sqlite3


In [82]:
import matplotlib.pyplot as plt

In [3]:
new = sqlite3.connect("./brass.db")

new.execute("CREATE TABLE DA (id PRIMARY KEY, name,number);")

for i in range(5):
    new.execute("insert into DA (id,name,number) values (?,?,?)",(i,"mango",456788))
    new.commit()

new.close()



In [5]:
new = sqlite3.connect("./brass.db")

cursor = new.execute("SELECT id, name from DA")
for row in cursor:
    print(row)

new.close()

(0, 'mango')
(1, 'mango')
(2, 'mango')
(3, 'mango')
(4, 'mango')


In [6]:
from pandas import *

In [8]:
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df2 = DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})

In [9]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [10]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [11]:
merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [13]:
merge(df1, df2,on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [20]:
data = DataFrame({'k1': ['one'] * 3 + ['two'] * 4,'k2': [1, 1, 2, 3, 3, 4, 4]})


In [18]:
['two'] * 4+['one'] * 3

['two', 'two', 'two', 'two', 'one', 'one', 'one']

In [21]:
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [22]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [25]:
data.drop_duplicates(inplace=True)

In [26]:
data

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [27]:
data

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [31]:
df3=ExcelFile("./Course Syllabus.xlsx")

In [32]:
df3.sheet_names

['Basic Python',
 'Advanced Python',
 'Datascience with Python',
 'Machine Learning',
 'Deep Learning']

In [33]:
df4=read_excel(df3,sheet_name='Deep Learning')

In [34]:
df4

Syllabus    Duration
0   1. Introduction to Deep Learning (DL)     90 mins
1     2. Neural Network (NN) introduction    240 mins
2                   Neurons and the Brain         NaN
3                   Non-linear Hypothesis         NaN
4                              perceptron         NaN
5                   Multilayer perceptron         NaN
6               Training a neural network         NaN
7                  Backpropagation primer         NaN
8                Gradients & optimization         NaN
9             3. Deep Learning for images    180 mins
10                       CNN architecture         NaN
11   Overview of modern CNN architectures         NaN
12                       pre-trained CNNs         NaN
13                      Alexnet/Googlenet         NaN
14                            OpenCV + NN         NaN
15              3. Deep Learning for Text    150 mins
16                                    RNN         NaN
17                                   LSTM         NaN
18                                    GRU         NaN
19      4.preprocessing Techniques for DL    120 mins
20                         5.Tools for DL    150 mins
21                             6.Practise    180 mins
22                                    NaN         NaN
23                                  Total  18.5 hours

In [35]:
df4.dropna()

Syllabus    Duration
0   1. Introduction to Deep Learning (DL)     90 mins
1     2. Neural Network (NN) introduction    240 mins
9             3. Deep Learning for images    180 mins
15              3. Deep Learning for Text    150 mins
19      4.preprocessing Techniques for DL    120 mins
20                         5.Tools for DL    150 mins
21                             6.Practise    180 mins
23                                  Total  18.5 hours

In [36]:
df4.dropna(inplace=True)

In [37]:
df4

Syllabus    Duration
0   1. Introduction to Deep Learning (DL)     90 mins
1     2. Neural Network (NN) introduction    240 mins
9             3. Deep Learning for images    180 mins
15              3. Deep Learning for Text    150 mins
19      4.preprocessing Techniques for DL    120 mins
20                         5.Tools for DL    150 mins
21                             6.Practise    180 mins
23                                  Total  18.5 hours

In [38]:
df = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(6)})


In [39]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [40]:
get_dummies(df['key'])
#one hot encoding

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [41]:
def add(a):
    return a+10

In [42]:
g = [2,5,6,7,9,1]

In [48]:
import time
start = time.time()
for i in g:
    print(add(i))
print(time.time()-start)

12
15
16
17
19
11
0.0009891986846923828


In [49]:
sta = time.time()
list(map(add,g))
print(time.time()-sta)

0.00031757354736328125


In [50]:
data1 = DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham',
'nova lox'],'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [51]:
data1

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [52]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

In [54]:
data1['animal'] = data1['food'].map(str.lower).map(meat_to_animal)


In [55]:
data1

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [ ]:
https://github.com/sharmasaravanan/Machine_learning

In [56]:
s = Series(np.random.randn(6))



In [57]:
s

0    2.864599
1    0.193810
2    0.510212
3    0.078687
4   -0.837827
5   -0.869087
dtype: float64

In [58]:
s[::2] = np.nan


In [59]:
s

0         NaN
1    0.193810
2         NaN
3    0.078687
4         NaN
5   -0.869087
dtype: float64

In [60]:
s.fillna(s.mean())


0   -0.198863
1    0.193810
2   -0.198863
3    0.078687
4   -0.198863
5   -0.869087
dtype: float64

In [62]:
s.fillna(method='ffill')

0         NaN
1    0.193810
2    0.193810
3    0.078687
4    0.078687
5   -0.869087
dtype: float64

In [63]:
s.fillna(method='bfill')

0    0.193810
1    0.193810
2    0.078687
3    0.078687
4   -0.869087
5   -0.869087
dtype: float64