In [15]:
from sklearn.preprocessing import LabelEncoder,MultiLabelBinarizer

In [17]:
en = LabelEncoder()
oh = MultiLabelBinarizer()

In [3]:
outlook = ["sunny","sunny","overcast","rainy","rainy","rainy","overcast","sunny","sunny","rainy","sunny","overcast","overcast","rainy"]

In [4]:
outlook

['sunny',
 'sunny',
 'overcast',
 'rainy',
 'rainy',
 'rainy',
 'overcast',
 'sunny',
 'sunny',
 'rainy',
 'sunny',
 'overcast',
 'overcast',
 'rainy']

In [5]:
import pandas as pd

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [6]:
data = pd.read_csv("./weather.csv")

In [10]:
data.outlook.tolist()

[2, 2, 1, 0, 0, 0, 1, 2, 2, 0, 2, 1, 1, 0]

In [11]:
en.fit_transform(outlook)

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [52]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [53]:
data.columns

Index(['outlook', 'temperature', 'humidity', 'wind', 'play'], dtype='object')

In [54]:
x = data[['outlook', 'temperature', 'humidity', 'wind']]

In [55]:
y = data.play

In [65]:
model = DecisionTreeClassifier(criterion="entropy")

In [66]:
model.fit(x,y)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [67]:
model.predict([[0,0,1,0]])

array(['yes'], dtype=object)

In [68]:
model.predict_proba([[0,0,1,0]])

array([[0., 1.]])

In [69]:
model.classes_

array(['no', 'yes'], dtype=object)

In [70]:
model.predict([[2,1,1,1]])

array(['no'], dtype=object)

In [71]:
model.predict_proba([[2,1,1,1]])

array([[1., 0.]])