In [6]:
class A:
    def show(self,name):
        self.name=name
        print(self.name)

In [8]:
a = A()
a.show("mango")

mango


In [17]:

class B:
    def show(self,fruit):
        self.fruit=fruit
        print(self.fruit)
    def add(self,e,f):
        print(e+f)

In [18]:
b=B()

In [19]:
b.show("orange")

orange


In [21]:
b.add(25,100)

125


In [ ]:
https://github.com/sharmasaravanan/MSME-python

In [ ]:
https://github.com/sharmasaravanan/Machine_learning

In [24]:
class C:
    def __init__(self,fruit,a,b):
        self.fruit=fruit
        self.a=a
        self.b=b
    def show(self):
        print(self.fruit)
    def add(self):
        print(self.a+self.b)

In [26]:
c = C("mango",45,12)

In [27]:
c.add()

57


In [28]:
c.show()

mango


In [29]:
c.a

45

In [30]:
class D:
    x=14
    def mul(self,y):
        self.y=y
        print(self.y*D.x)

In [31]:
d = D()

In [32]:
d.mul(5)

70


In [33]:
D.x

14

In [34]:
d.x

14

In [41]:
#inheritance
class A:
    def __init__(self, name):
        self.name = name

    def show(self):
        print('name: %s' % (self.name))
        #print(self.fruit)


class B(A):
    def __init__(self, name, fruit):
        #A.__init__(self, name)
        self.name=name
        self.fruit = fruit

    def show(self):
        A.show(self)
        print('Fruit: %s' % (self.fruit))


f = B("apple", "mango")
f.show()

name: apple
Fruit: mango


In [48]:
#method overloading
class E:
    def add(self,a,b,c=None):
        if c:
            print(a*b*c)
        else:
            print(a*b)

In [50]:
e= E()
e.add(5,2,4)

40


In [51]:
name="apple"

In [54]:
name.replace('a','A')

'Apple'

In [55]:
print()

In [59]:
#method overiding
class Parent:
    def myMethod(self):
        print('Calling parent method')


class Child(Parent):
    def myMethod(self,name):
        print('Calling child method',name)


c = Child()
c.myMethod()

p = Parent()
p.myMethod()

TypeError: myMethod() missing 1 required positional argument: 'name'

In [60]:
a=10

In [61]:
a

10

In [62]:
a=15

In [63]:
a

15

In [ ]:
void main()
int main()

if __name__ == "__main__":

In [64]:
from flask import Flask,request,jsonify #Django,cherrypy,bottle
import json

app=Flask(__name__)

@app.route('/python',methods=['POST','GET'])
def home():
    if request.method=='POST':
             data=request.args.get('d')#request.args['q']
             #data = request.values.get('key')
             print(data)
             res='{'+'"Name":"{}"'.format(data)+'}'
             print(json.loads(res))
             return jsonify(res)
             #return json.dumps(json.loads(res))
             


if __name__=='__main__':
    app.run()

UnsupportedOperation: not writable

In [ ]:
https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4 
https://sourceforge.net/projects/pyqt/

In [1]:
import pandas as pd

In [17]:
#text file 

In [5]:
txtFile=open("MSME_Python(2).txt","a")
txtFile.write("hi,hello\n")
txtFile.write("how are you?\n")
txtFile.close()

In [13]:
readtxt=open("MSME_Python(2).txt","r")
readtxt.readlines()

['hi,hello\n', 'hello\n', 'how are you?\n', 'hi,hello\n', 'how are you?\n']

In [16]:
readtxt.readline()

''

In [27]:
df=pd.read_csv("./Advertising.csv",index_col=0,header=0)

In [28]:
df.head(3)

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3

In [30]:
data={"fruit":["apple","mango","orange"],"vegetable":["onion","potato","beans"]}

In [34]:
df1 = pd.DataFrame(data,index=["a","b","c"])

In [35]:
df1

fruit vegetable
a   apple     onion
b   mango    potato
c  orange     beans

In [44]:
a=["apple","mango","pine apple"]
b=["onion","potato","carrot"]

In [39]:
b=pd.DataFrame(b)

0
0   onion
1  potato
2  carrot

In [47]:
df1["fruits 2"]=a

In [48]:
df1

fruit vegetable    fruits 2 vegetable 2
a   apple     onion       apple       onion
b   mango    potato       mango      potato
c  orange     beans  pine apple      carrot

In [72]:
df1.to_csv("fruits_vege.tsv",sep='\t')

In [70]:
df2=pd.read_csv("labeledTrainData.tsv",delimiter="\t",quoting=3)

In [71]:
df2.head()

id  sentiment                                             review
0  "5814_8"          1  "With all this stuff going down at the moment ...
1  "2381_9"          1  "\"The Classic War of the Worlds\" by Timothy ...
2  "7759_3"          0  "The film starts with a manager (Nicholas Bell...
3  "3630_4"          0  "It must be assumed that those who praised thi...
4  "9495_8"          1  "Superbly trashy and wondrously unpretentious ...

In [78]:
df3=pd.read_excel("./Course Syllabus.xlsx",sheet_name='Datascience with Python')

In [75]:
exc=pd.ExcelFile("./Course Syllabus.xlsx")

In [77]:
exc.sheet_names

['Basic Python',
 'Advanced Python',
 'Datascience with Python',
 'Machine Learning',
 'Deep Learning']

In [83]:
df3=pd.read_excel(exc,sheet_name="Datascience with Python")

In [84]:
df3.iloc[4]

Syllabus    DataFrame Indexing and Loading
Duration                         1.5 hours
Name: 4, dtype: object

In [85]:
import json


In [86]:
jsonFile=open("test.json")
jsonData=json.load(jsonFile)

In [89]:
jsonData

{'domainId': 'DOMAIN-100',
 'question': 'I want to book appointment',
 'language': 'EN_US',
 'type': 'TASK'}

In [91]:
import yaml

In [94]:
ymlFile=open("./config_sample.yml")
ymlData=yaml.load(ymlFile)

In [95]:
ymlData

{'language': 'en',
 'pipeline': 'spacy_sklearn',
 'data': [True, 'yep', 'bye', 'goodbye', False]}

In [96]:
import sqlite3

In [104]:
import re

string = "Python is a scripting language.Python is easy to learn"

match_obj = re.match(r'easy', string)

print(match_obj)

search_obj = re.search(r'Python', string)

print(search_obj.group(0))

find_obj = re.findall(r'Python',string)

print(find_obj)

None
Python
['Python', 'Python']


In [105]:
print(re.sub(r'Python', r'AI', string))


AI is a scripting language.AI is easy to learn


In [109]:
print(re.findall(r'\w', string))
print("-----"*8)

print(re.findall(r'\w*', string))
print("-----"*8)

print(re.findall(r'\w+', string))
print("-----"*8)

print(re.findall(r'^\w+', string))
print("-----"*8)

print(re.findall(r'\w+$', string))
print("-----"*8)


['P', 'y', 't', 'h', 'o', 'n', 'i', 's', 'a', 's', 'c', 'r', 'i', 'p', 't', 'i', 'n', 'g', 'l', 'a', 'n', 'g', 'u', 'a', 'g', 'e', 'P', 'y', 't', 'h', 'o', 'n', 'i', 's', 'e', 'a', 's', 'y', 't', 'o', 'l', 'e', 'a', 'r', 'n']
----------------------------------------
['Python', '', 'is', '', 'a', '', 'scripting', '', 'language', '', 'Python', '', 'is', '', 'easy', '', 'to', '', 'learn', '']
----------------------------------------
['Python', 'is', 'a', 'scripting', 'language', 'Python', 'is', 'easy', 'to', 'learn']
----------------------------------------
['Python']
----------------------------------------
['learn']
----------------------------------------


In [ ]:
^ -> starting char/word
$ -> ending char/word

In [112]:
print(re.findall(r'@(\w+)', "test@gmail.com"))

print(re.findall(r'@\w+.\w+', "test@gmail.com"))

print(re.findall(r'@\w+.(\w+)', "test@gmail.com"))

['gmail']
['@gmail.com']
['com']


In [116]:
print(re.findall(r'\d{2}-\d{2}-\d{4}', "john's date of birth is 11-11-2001,12-11-2003"))

print(re.findall(r'\d{2}-\d{2}-(\d{4})', "john's date of birth is 11-11-2001"))

['11-11-2001', '12-11-2003']
['2001']


In [117]:
print(re.findall(r'[aeiouAEIOU]\w+', string))

print(re.findall(r'\b[aeiouAEIOU]\w+', string))

print(re.findall(r'\b[^aeiouAEIOU ]\w+', string))


['on', 'is', 'ipting', 'anguage', 'on', 'is', 'easy', 'earn']
['is', 'is', 'easy']
['Python', 'scripting', 'language', '.Python', 'to', 'learn']


In [122]:
sent = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~"

In [126]:
re.findall(r'[^A-Fa-f0-4]',sent)

['g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '5',
 '6',
 '7',
 '8',
 '9',
 '!',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~']

In [131]:
val = '999994561245'

if (re.match(r'[8-9]{1}[0-5]{5}', val)):
    print('yes')



In [132]:
text = "abc,def;ghi jkl"
print(re.split(r'[;,\s]', text))

print(re.sub(r'[;,\s]', ' ', text))

html = '<tr align="center"><td>5</td> <td>William</td> <td>Ava</td></tr>'

print(re.findall(r'<td>\w+</td>\s<td>(\w+)</td', html))

['abc', 'def', 'ghi', 'jkl']
abc def ghi jkl
['William']


In [133]:
l=[5,4,6,7,9,8,1,2,3]

In [135]:
import numpy as np

In [137]:
m=np.reshape(l,[3,3])

In [138]:
m

array([[5, 4, 6],
       [7, 9, 8],
       [1, 2, 3]])

In [139]:
m[0]

array([5, 4, 6])

In [140]:
m[:,0]

array([5, 7, 1])

In [141]:
m[1][1]

9

In [ ]:
https://w3resource.com/python-exercises/

In [10]:
import calendar as cal
c = cal.TextCalendar(cal.SUNDAY)
print(c.formatmonth(2019,9))

   September 2019
Su Mo Tu We Th Fr Sa
 1  2  3  4  5  6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30



In [14]:
for name in cal.day_name:
    print(name)
cal.calendar?

Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday


In [17]:
print (cal.calendar(2012)) 



                                  2012

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                   1             1  2  3  4  5                1  2  3  4
 2  3  4  5  6  7  8       6  7  8  9 10 11 12       5  6  7  8  9 10 11
 9 10 11 12 13 14 15      13 14 15 16 17 18 19      12 13 14 15 16 17 18
16 17 18 19 20 21 22      20 21 22 23 24 25 26      19 20 21 22 23 24 25
23 24 25 26 27 28 29      27 28 29                  26 27 28 29 30 31
30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                   1          1  2  3  4  5  6                   1  2  3
 2  3  4  5  6  7  8       7  8  9 10 11 12 13       4  5  6  7  8  9 10
 9 10 11 12 13 14 15      14 15 16 17 18 19 20      11 12 13 14 15 16 17
16 17 18 19 20 21 22      21 22 23 24 25 26 27      18 19 20 21 22 23 24
23 24 25 26 27 28 29   

In [16]:
cal.isleap(2018)

False

In [22]:
print (cal.leapdays(1950, 2000)) 
cal.LocaleTextCalendar?

12


In [21]:
c = cal.LocaleTextCalendar(locale='en_US')
c.prmonth(2017,7)

Error: unsupported locale setting