In [5]:
num = int(input("Enter the value for num :"))
if num%4==0:
    print("divisible by 4")
elif num%2==0:
    print("even")
else:
    print("odd")

Enter the value for num :5
odd


In [11]:
cnt=0
name="sharma"
while cnt<len(name):
    num = int(input("Enter the value for num :"))
    if num==15:
        print("Good bye..")
        break
    elif num==25:
        print("skipping..")
        continue
    elif num == 10:
        pass
    if num%4==0:
        print("divisible by 4")
    elif num%2==0:
        print("even")
    else:
        print("odd")
    cnt+=1

Enter the value for num :14
even
Enter the value for num :16
divisible by 4
Enter the value for num :18
even
Enter the value for num :19
odd
Enter the value for num :21
odd
Enter the value for num :48
divisible by 4


In [12]:
import random as r


In [15]:
 r.randint(0,99)

71

In [16]:
name = "apple"

In [19]:
name[1:4]

'ppl'

In [20]:
name[3]

'l'

In [21]:
name[:3]

'app'

In [22]:
name[2:]

'ple'

In [32]:
name[::-1]

'elppa'

In [27]:
name

'apple'

In [33]:
name.capitalize()

'Apple'

In [38]:
name[0:5:2]

'ape'

In [42]:
name.count("p")

2

In [43]:
name.endswith("le")

True

In [45]:
name.startswith("apl")

False

In [46]:
name.find('e')

4

In [48]:
name.index('le')

3

In [50]:
name.replace('a',"b")

'bpple'

In [51]:
name.isalnum()


True

In [52]:
name.isalpha()

True

In [53]:
name.isdecimal()

False

In [58]:
n='5.5'


In [59]:
n.isdecimal()

False

In [60]:
n.isdigit()

False

In [61]:
name.islower()

True

In [62]:
name.isupper()

False

In [63]:
name.isspace()

False

In [64]:
name = " apple "

In [66]:
name.lstrip()

'apple '

In [67]:
name.rstrip()

' apple'

In [68]:
name.strip()

'apple'

In [69]:
sent = "Elephant is an animal"

In [72]:
ss = sent.split('an')

In [73]:
ss

['Eleph', 't is ', ' ', 'imal']

In [76]:
"an".join(ss)

'Elephant is an animal'

Elephant is an animal . -> . animal an is Elephant 

In [80]:
" ".join(sent.split()[::-1])

'animal an is Elephant'

In [1]:
l=[]

In [3]:
ll=[1,2,3,4,5,'a','b','c','d',"apple","ball","cat"]

In [12]:
ll[3:11:3]

[4, 'b', 'apple']

In [9]:
len(ll)

12

In [13]:
ll[0]="dog"

In [15]:
ll.index('c')

7

In [16]:
ll[7]="mango"

In [17]:
ll

['dog', 2, 3, 4, 5, 'a', 'b', 'mango', 'd', 'apple', 'ball', 'cat']

In [18]:
l

[]

In [19]:
l.append("apple")

In [25]:
ll.append("orange")

In [22]:
ll

['dog', 2, 3, 4, 5, 'a', 'b', 'mango', 'd', 'apple', 'ball', 'cat', 'orange']

In [23]:
ll.insert(5,"elephant")

In [24]:
ll

['dog',
 2,
 3,
 4,
 5,
 'elephant',
 'a',
 'b',
 'mango',
 'd',
 'apple',
 'ball',
 'cat',
 'orange']

In [27]:
ll.pop()

'orange'

In [28]:
ll

['dog',
 2,
 3,
 4,
 5,
 'elephant',
 'a',
 'b',
 'mango',
 'd',
 'apple',
 'ball',
 'cat',
 'orange']

In [29]:
ll.remove(5)

In [30]:
ll

['dog',
 2,
 3,
 4,
 'elephant',
 'a',
 'b',
 'mango',
 'd',
 'apple',
 'ball',
 'cat',
 'orange']

In [31]:
ll.count(2)

1

In [32]:
l.clear()

In [34]:
ll

['dog',
 2,
 3,
 4,
 'elephant',
 'a',
 'b',
 'mango',
 'd',
 'apple',
 'ball',
 'cat',
 'orange']

In [35]:
 t=('dog',
 2,
 3,
 4,
 'elephant',
 'a',
 'b',
 'mango',
 'd',
 'apple',
 'ball',
 'cat',
 'orange')

In [37]:
t[2:6]


(3, 4, 'elephant', 'a')

In [39]:
t[2]=8

TypeError: 'tuple' object does not support item assignment

In [40]:
ll.sort()

TypeError: '<' not supported between instances of 'int' and 'str'

In [52]:
for i,j in enumerate(ll):
    print(i,j)

0 dog
1 2
2 3
3 4
4 elephant
5 a
6 b
7 mango
8 d
9 apple
10 ball
11 cat
12 orange


In [53]:
for i in range(len(a)):
    for j in range(len(b)):
        if a[i]==b[j]:
            print(a[i])


SyntaxError: unexpected EOF while parsing (<ipython-input-53-0770b38e38cd>, line 3)

In [ ]:
for i in a:
    for j in b:
        if i==j:
            print(a)

In [ ]:
set(a)&set(b)

In [ ]:
for i in a:
    if i <=7:
        c.append(i)

In [ ]:
c=[i for i in a if i<=7]

In [63]:
d={'a':'apple','b':'ball',2:'cat','d':4,2:"bat"}

In [55]:
d.keys()

dict_keys(['a', 'b', 2, 'd'])

In [56]:
d.values()

dict_values(['apple', 'ball', 'cat', 4])

In [61]:
d[4]="dog"

In [64]:
d

{'a': 'apple', 'b': 'ball', 2: 'bat', 'd': 4}

In [68]:
for i in d.items():
    print(i)

('a', 'apple')
('b', 'ball')
(2, 'bat')
('d', 4)


In [ ]:
user -> a-> adding     -> "The date of birth of john has been added to the database"
        b-> displaying -> "The date of birth of john is 01/01/01"

In [73]:
f = open("olive.txt","a")
f.write("\nhow do you do?")
f.close()

In [80]:
fr = open("olive.txt","r")
fr.readlines()

['hi hello\n', 'how are you?,\n', 'i am good\n', 'how do you do?']

In [79]:
fr.readline()

''

In [91]:
try:
    print(b)
except NameError:
    print("there is some error")
except ValueError
finally:
    a=10
    print(a)

there is some error
10


In [92]:
import random as r

In [93]:
import random

In [95]:
r.randint(0,20)

13

In [99]:
r.sample("apple",2)

['p', 'p']

In [103]:
r.choice(ll)

'mango'

In [104]:
from math import sin,cos,factorial

In [105]:
factorial(5)

120

In [106]:
from math import *

In [ ]:
A-Z,a-z,0-9,

In [ ]:
#function

In [17]:
def add(a,b=15):
    return a+b,a*b


In [18]:
c=int(input("a: "))
#d=int(input("b: "))
s,m=add(c)
print("Addition is:",s,"\nMultiplication is :",m)

a: 5
Addition is: 20 
Multiplication is : 75


In [6]:
s

40

In [7]:
m

300

In [19]:
ind=[1,2,3,4,5,6,7,8,9]

In [20]:
import numpy as np

In [29]:
M=np.reshape(ind,[3,3])

In [30]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
M[2]

array([7, 8, 9])

In [36]:
M[:,1]

array([2, 5, 8])

In [38]:
M[2][1]


8