In [5]:
num = int(input("Enter the value for num :"))
if num%4==0:
    print("divisible by 4")
elif num%2==0:
    print("even")
else:
    print("odd")

Enter the value for num :5
odd


In [11]:
cnt=0
name="sharma"
while cnt<len(name):
    num = int(input("Enter the value for num :"))
    if num==15:
        print("Good bye..")
        break
    elif num==25:
        print("skipping..")
        continue
    elif num == 10:
        pass
    if num%4==0:
        print("divisible by 4")
    elif num%2==0:
        print("even")
    else:
        print("odd")
    cnt+=1

Enter the value for num :14
even
Enter the value for num :16
divisible by 4
Enter the value for num :18
even
Enter the value for num :19
odd
Enter the value for num :21
odd
Enter the value for num :48
divisible by 4


In [12]:
import random as r


In [15]:
 r.randint(0,99)

71

In [16]:
name = "apple"

In [19]:
name[1:4]

'ppl'

In [20]:
name[3]

'l'

In [21]:
name[:3]

'app'

In [22]:
name[2:]

'ple'

In [32]:
name[::-1]

'elppa'

In [27]:
name

'apple'

In [33]:
name.capitalize()

'Apple'

In [38]:
name[0:5:2]

'ape'

In [42]:
name.count("p")

2

In [43]:
name.endswith("le")

True

In [45]:
name.startswith("apl")

False

In [46]:
name.find('e')

4

In [48]:
name.index('le')

3

In [50]:
name.replace('a',"b")

'bpple'

In [51]:
name.isalnum()


True

In [52]:
name.isalpha()

True

In [53]:
name.isdecimal()

False

In [58]:
n='5.5'


In [59]:
n.isdecimal()

False

In [60]:
n.isdigit()

False

In [61]:
name.islower()

True

In [62]:
name.isupper()

False

In [63]:
name.isspace()

False

In [64]:
name = " apple "

In [66]:
name.lstrip()

'apple '

In [67]:
name.rstrip()

' apple'

In [68]:
name.strip()

'apple'

In [69]:
sent = "Elephant is an animal"

In [72]:
ss = sent.split('an')

In [73]:
ss

['Eleph', 't is ', ' ', 'imal']

In [76]:
"an".join(ss)

'Elephant is an animal'

Elephant is an animal . -> . animal an is Elephant 

In [80]:
" ".join(sent.split()[::-1])

'animal an is Elephant'

In [1]:
l=[]

In [3]:
ll=[1,2,3,4,5,'a','b','c','d',"apple","ball","cat"]

In [12]:
ll[3:11:3]

[4, 'b', 'apple']

In [9]:
len(ll)

12

In [13]:
ll[0]="dog"

In [15]:
ll.index('c')

7

In [16]:
ll[7]="mango"

In [17]:
ll

['dog', 2, 3, 4, 5, 'a', 'b', 'mango', 'd', 'apple', 'ball', 'cat']

In [18]:
l

[]

In [19]:
l.append("apple")

In [25]:
ll.append("orange")

In [22]:
ll

['dog', 2, 3, 4, 5, 'a', 'b', 'mango', 'd', 'apple', 'ball', 'cat', 'orange']

In [23]:
ll.insert(5,"elephant")

In [24]:
ll

['dog',
 2,
 3,
 4,
 5,
 'elephant',
 'a',
 'b',
 'mango',
 'd',
 'apple',
 'ball',
 'cat',
 'orange']

In [27]:
ll.pop()

'orange'

In [28]:
ll

['dog',
 2,
 3,
 4,
 5,
 'elephant',
 'a',
 'b',
 'mango',
 'd',
 'apple',
 'ball',
 'cat',
 'orange']

In [29]:
ll.remove(5)

In [30]:
ll

['dog',
 2,
 3,
 4,
 'elephant',
 'a',
 'b',
 'mango',
 'd',
 'apple',
 'ball',
 'cat',
 'orange']

In [31]:
ll.count(2)

1

In [32]:
l.clear()

In [34]:
ll

['dog',
 2,
 3,
 4,
 'elephant',
 'a',
 'b',
 'mango',
 'd',
 'apple',
 'ball',
 'cat',
 'orange']

In [35]:
 t=('dog',
 2,
 3,
 4,
 'elephant',
 'a',
 'b',
 'mango',
 'd',
 'apple',
 'ball',
 'cat',
 'orange')

In [37]:
t[2:6]


(3, 4, 'elephant', 'a')

In [39]:
t[2]=8

TypeError: 'tuple' object does not support item assignment

In [40]:
ll.sort()

TypeError: '<' not supported between instances of 'int' and 'str'

In [52]:
for i,j in enumerate(ll):
    print(i,j)

0 dog
1 2
2 3
3 4
4 elephant
5 a
6 b
7 mango
8 d
9 apple
10 ball
11 cat
12 orange


In [53]:
for i in range(len(a)):
    for j in range(len(b)):
        if a[i]==b[j]:
            print(a[i])


SyntaxError: unexpected EOF while parsing (<ipython-input-53-0770b38e38cd>, line 3)

In [ ]:
for i in a:
    for j in b:
        if i==j:
            print(a)

In [ ]:
set(a)&set(b)

In [ ]:
for i in a:
    if i <=7:
        c.append(i)

In [ ]:
c=[i for i in a if i<=7]

In [63]:
d={'a':'apple','b':'ball',2:'cat','d':4,2:"bat"}

In [55]:
d.keys()

dict_keys(['a', 'b', 2, 'd'])

In [56]:
d.values()

dict_values(['apple', 'ball', 'cat', 4])

In [61]:
d[4]="dog"

In [64]:
d

{'a': 'apple', 'b': 'ball', 2: 'bat', 'd': 4}

In [68]:
for i in d.items():
    print(i)

('a', 'apple')
('b', 'ball')
(2, 'bat')
('d', 4)


In [ ]:
user -> a-> adding     -> "The date of birth of john has been added to the database"
        b-> displaying -> "The date of birth of john is 01/01/01"

In [73]:
f = open("olive.txt","a")
f.write("\nhow do you do?")
f.close()

In [80]:
fr = open("olive.txt","r")
fr.readlines()

['hi hello\n', 'how are you?,\n', 'i am good\n', 'how do you do?']

In [79]:
fr.readline()

''

In [91]:
try:
    print(b)
except NameError:
    print("there is some error")
except ValueError
finally:
    a=10
    print(a)

there is some error
10


In [92]:
import random as r

In [93]:
import random

In [95]:
r.randint(0,20)

13

In [99]:
r.sample("apple",2)

['p', 'p']

In [103]:
r.choice(ll)

'mango'

In [104]:
from math import sin,cos,factorial

In [105]:
factorial(5)

120

In [106]:
from math import *

In [ ]:
A-Z,a-z,0-9,

In [ ]:
#function

In [17]:
def add(a,b=15):
    return a+b,a*b


In [18]:
c=int(input("a: "))
#d=int(input("b: "))
s,m=add(c)
print("Addition is:",s,"\nMultiplication is :",m)

a: 5
Addition is: 20 
Multiplication is : 75


In [6]:
s

40

In [7]:
m

300

In [19]:
ind=[1,2,3,4,5,6,7,8,9]

In [20]:
import numpy as np

In [29]:
M=np.reshape(ind,[3,3])

In [30]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
M[2]

array([7, 8, 9])

In [36]:
M[:,1]

array([2, 5, 8])

In [38]:
M[2][1]


8

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.cross_validation import train_test_split
from sklearn import metrics
import pickle

/usr/local/lib/python3.6/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [4]:
data = pd.read_csv("./Advertising.csv",index_col=0)

In [5]:
data.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [38]:
x = data[["TV","radio","newspaper"]]

In [39]:
y =  data.sales

In [40]:
X_train, X_test, y_train, y_test = train_test_split(x, y)


In [41]:
model = LinearRegression()

In [42]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [43]:
y_pred = model.predict(X_test)

print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))


1.6616119550105768


In [45]:
model.predict([[75,75,75]])

array([20.33113237])

In [46]:
fname="model_olive.sav"

pickle.dump(model, open(fname, 'wb'))

In [4]:
import pickle
fname="model_olive.sav"
loaded_model=pickle.load(open(fname, 'rb'))

In [5]:
loaded_model.predict([[75,75,75]])

array([20.33113237])

In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [8]:
df = pd.read_csv("./labeledTrainData.tsv",delimiter="\t")

In [9]:
df.head()

id  sentiment                                             review
0  5814_8          1  With all this stuff going down at the moment w...
1  2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...
2  7759_3          0  The film starts with a manager (Nicholas Bell)...
3  3630_4          0  It must be assumed that those who praised this...
4  9495_8          1  Superbly trashy and wondrously unpretentious 8...

In [10]:
df.dropna(inplace=True)


In [11]:
df["rated"]=np.where(df['sentiment']>0,1,0)


In [12]:
df.head()

id  sentiment                                             review  rated
0  5814_8          1  With all this stuff going down at the moment w...      1
1  2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...      1
2  7759_3          0  The film starts with a manager (Nicholas Bell)...      0
3  3630_4          0  It must be assumed that those who praised this...      0
4  9495_8          1  Superbly trashy and wondrously unpretentious 8...      1

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df['review'],df['rated'])


In [15]:
vect=CountVectorizer(min_df=5,ngram_range=(1,2)).fit(X_train)

X_train_vetorised=vect.transform(X_train)

In [16]:
X_train_vetorised

<18750x123312 sparse matrix of type '<class 'numpy.int64'>'
	with 5107580 stored elements in Compressed Sparse Row format>

In [17]:
model=LogisticRegression()

model.fit(X_train_vetorised,y_train)

predictions=model.predict(vect.transform(X_test))

In [18]:
accuracy_score(y_true=y_test,y_pred=predictions)

0.89072

In [21]:
testing=input("Enter the sentence for testing: ")

print(model.predict(vect.transform([testing])))

Enter the sentence for testing: the movie was not good at all.
[0]


In [20]:

feature_name=np.array(vect.get_feature_names())

sort_coeff=model.coef_[0].argsort()

print ("small coeff : {}",format(feature_name[sort_coeff[:10]]))

print ("large coeff : {}",format(feature_name[sort_coeff[:-11:-1]]))

small coeff : {} ['worst' 'awful' 'waste' 'boring' 'disappointment' 'lacks' 'poorly'
 'terrible' 'worse' 'poor']
large coeff : {} ['excellent' 'perfect' 'superb' 'wonderful' 'enjoyable' 'amazing'
 'better than' 'today' 'very good' '10 10']


In [22]:
vect.get_feature_names()

['00',
 '00 and',
 '00 in',
 '000',
 '000 00',
 '000 000',
 '000 and',
 '000 for',
 '000 the',
 '000 to',
 '000 year',
 '000 years',
 '007',
 '01',
 '02',
 '03',
 '05',
 '06',
 '07',
 '08',
 '09',
 '10',
 '10 000',
 '10 10',
 '10 15',
 '10 and',
 '10 as',
 '10 at',
 '10 because',
 '10 bethany',
 '10 br',
 '10 but',
 '10 dir',
 '10 don',
 '10 favorite',
 '10 for',
 '10 from',
 '10 good',
 '10 if',
 '10 in',
 '10 instead',
 '10 is',
 '10 it',
 '10 items',
 '10 just',
 '10 line',
 '10 lines',
 '10 million',
 '10 minute',
 '10 minutes',
 '10 movie',
 '10 movies',
 '10 my',
 '10 no',
 '10 not',
 '10 of',
 '10 on',
 '10 only',
 '10 or',
 '10 out',
 '10 overall',
 '10 people',
 '10 points',
 '10 rating',
 '10 seconds',
 '10 star',
 '10 stars',
 '10 that',
 '10 the',
 '10 there',
 '10 this',
 '10 times',
 '10 to',
 '10 was',
 '10 worst',
 '10 would',
 '10 year',
 '10 years',
 '100',
 '100 000',
 '100 films',
 '100 greatest',
 '100 million',
 '100 minutes',
 '100 movies',
 '100 of',
 '100 sure'