In [2]:
a=8
b=7
print a+b


15


In [4]:
print "hello world"

hello world


In [5]:
a=85
name="apple"

In [6]:
print name

apple


In [9]:
print "hello "+name+" fruit"

hello apple fruit


In [11]:
print "hello "+ str(a)

hello 85


In [12]:
float(a)

85.0

In [17]:
print "hello",a,"world",name,88


hello 85 world apple 88


In [23]:

d=input('Enter the numerical input :')#integer
f=raw_input('Enter the string input :')#string


Enter the numerical input :5
Enter the string input :6


In [27]:
type(f)

str

In [42]:
a=5

In [43]:
a=str(a)

In [44]:
int(a)+int(a+a)+int(a+a+a)

615

In [28]:
#if-else
num=input("Enter any number: ")
if num%2==0:
    print "Number",num,"is even"
else:
    print "Number",num,"is odd"

Enter any number: 25
Number 25 is odd


In [31]:
#elif
num=input("Enter any number: ")
if num%4==0:
    print "Number",num,"is divisible by 4 and also its a even"
elif num%2==0:
    print "Number",num,"is even"
else:
    print "Number",num,"is odd"

Enter any number: 5
Number 5 is odd


In [26]:
#while loop
while 1:
    num=input("Enter any number: ")
    if num==10:
        break
    elif num==15:
        continue
    if num%4==0:
        print "Number",num,"is divisible by 4 and also its a even"
    elif num%2==0:
        print "Number",num,"is even"
    else:
        print "Number",num,"is odd"


Enter any number: 45
Number 45 is odd
Enter any number: 15
Enter any number: 14
Number 14 is even
Enter any number: 10


In [59]:
name="sharma.txt"

In [65]:
l=sent.split(" ")

In [68]:
" ".join(l)

'my name is sharma is my name'

In [71]:
import math as m

In [74]:
m.factorial(5)

120

In [75]:
5*4*3*2*1


120

In [27]:
#list,
l=[1,"a","apple",2,"b","ball",1,3,2,"a"]


In [78]:
name="s h a r m a"

In [80]:
s=name.split(" ")

In [83]:
"@".join(s)

's@h@a@r@m@a'

In [59]:
l.sort()

In [57]:
l.reverse()

In [36]:
l[2]="mango"

In [53]:
el=[]

In [55]:
el.append(l)

In [61]:
del el[0]

In [16]:
l

[1, 'a', 'apple', 2, 'b', 'ball', 1, 3, 2, 'a']

In [84]:
days=("Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday")

In [86]:
days[0]=2

TypeError: 'tuple' object does not support item assignment

In [87]:
d={"a":"apple","b":"ball","c":"cat",1:"dog","e":3}

In [92]:
d

{1: 'dog', 'a': 'apple', 'b': 'ball', 'c': 'cat', 'e': 3, 'f': 3}

In [98]:
for i in range(0,10):
    print i
    

0
1
2
3
4
5
6
7
8
9


In [99]:
a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [101]:
c=[]
for i in a:
    if i in b:
        c.append(i)

In [102]:
c

[1, 1, 2, 3, 5, 8, 13]

a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


  a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
  b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]`

 a = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

palindrome 

In [2]:
import random as r

In [3]:
min=0
max=100

In [4]:
attempt=0
while 1:
    comp=r.randint(min,max)
    print "Isn't it %d ?"%comp
    user=raw_input("\nEnter the option \n a.high \n b.low \n c.Bingo \n")
    attempt+=1
    if user=="low" or user=="b":
        min=comp
        continue
    elif user=="high" or user=="a":
        max=comp
        continue
    elif user=="bingo" or user=="c":
        print "\nThe number is in your mind is %d and computer took %d attempts"%(comp,attempt)
        break
    else:
        print "\nPlease enter the valid option"

Isn't it 45 ?

Enter the option 
 a.high 
 b.low 
 c.Bingo 
a
Isn't it 8 ?

Enter the option 
 a.high 
 b.low 
 c.Bingo 
low
Isn't it 33 ?

Enter the option 
 a.high 
 b.low 
 c.Bingo 
high
Isn't it 10 ?

Enter the option 
 a.high 
 b.low 
 c.Bingo 
low
Isn't it 27 ?

Enter the option 
 a.high 
 b.low 
 c.Bingo 
high
Isn't it 23 ?

Enter the option 
 a.high 
 b.low 
 c.Bingo 
high
Isn't it 23 ?

Enter the option 
 a.high 
 b.low 
 c.Bingo 
high
Isn't it 20 ?

Enter the option 
 a.high 
 b.low 
 c.Bingo 
high
Isn't it 11 ?

Enter the option 
 a.high 
 b.low 
 c.Bingo 
bingo

The number is in your mind is 11 and computer took 9 attempts


In [12]:
a=3.2245455484548

In [14]:
print "%0.2f"%a

3.22


In [4]:
import random as r
num=str(r.randint(100,999))
print num   
j=0
while 1:
    user=raw_input("Enter your guess: ")
    cowbull = [0,0]
    if user=="quit" or user=="q":
        print "good bye..." 
        break  
    for i in range(len(num)):
        if num[i]==user[i]:
            cowbull[0]+=1
    b=len(set(num)&set(user))
    cowbull[1]=b-cowbull[0]
    j+=1
    if cowbull[0]==3:
        print "you win after",j,"attempts"
        break
    else:
        print("Your guess isn't quite right, try again.")
    print cowbull

314
Enter your guess: q
good bye...


In [27]:
num

'247'

In [29]:
user='374'

In [32]:
len(set(num)&set(user))

2

In [1]:
import random

In [ ]:
random.randint

In [2]:
import math as m

In [3]:
m.factorial(5)

120

In [4]:
from math import *

In [6]:
sqrt(16)

4.0

In [7]:
from math import sin,cos,factorial

In [9]:
s="abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()_-+=|\~`"

In [13]:
len=4

In [22]:
print "".join(random.sample(s,len))

xZv`


In [19]:
m.sqrt(5)

2.23606797749979

Welcome to the birthday dictionary. We know the birthdays of:
  <br>  Albert Einstein
  <br>  Benjamin Franklin
  <br>  Ada Lovelace

Who's birthday do you want to look up?
  <br>  Benjamin Franklin

Benjamin Franklin's birthday is 01/17/1706.

########################################

My name is sharma -> sharma is name My

In [23]:
di={1:5,3:45}

In [25]:
for i in di:
    print i

1
3


In [44]:
import sys
while 1:
    try:
        a=6
        print list(a)
    except (NameError,TypeError):
        sys.exit()
        print "there is an error"


SystemExit: 

In [56]:
doc=open("./test.txt","w")
doc.write("Hello,How are you?")
doc.write("\n")
doc.writelines("Hi, I am fine., what about you??\n")
doc.write("apple")
doc.close()

In [68]:
doc1=open("./test.txt","r")


In [69]:
doc1.readlines()

['Hello,How are you?\n', 'Hi, I am fine., what about you??\n', 'apple']

In [70]:
t=(('q','w'),(4,5))

In [71]:
t

(('q', 'w'), (4, 5))

In [78]:
for i in t:
    print i[0],i[1]

q w
4 5


 -- -- -- 
|  |  |  |  

In [85]:
a = '---'.join('    ')
b = '   '.join('||||')
print('\n'.join((a, b, a, b, a, b, a)))

 --- --- --- 
|   |   |   |
 --- --- --- 
|   |   |   |
 --- --- --- 
|   |   |   |
 --- --- --- 


In [87]:
b

'|   |   |   |'

If a game of Tic Tac Toe is represented as a list of lists, like so:

game = [[1, 2, 0],<br>
	[2, 1, 0],<br>
	[2, 1, 1]] <br>
where a 0 means an empty square, a 1 means that player 1 put their token in that space, and a 2 means that player 2 put their token in that space.

In [88]:
import numpy as np

In [89]:
a=np.array([[1,2,0],[2,1,0],[2,1,1]])

In [90]:
a

array([[1, 2, 0],
       [2, 1, 0],
       [2, 1, 1]])

In [117]:
b=[1,2,0,2,1,0,2,1,1]

In [97]:
np.asmatrix(b)

matrix([[1, 2, 0, 2, 1, 0, 2, 1, 1]])

In [111]:
def tictactoe(a,b):
    return a+b,a*b

In [113]:
a=input("Enter :")
b=input("Enter :")
c,d=tictactoe(a,b)

Enter :5
Enter :4


In [118]:
b

[1, 2, 0, 2, 1, 0, 2, 1, 1]

In [121]:
b=np.reshape(b,(3,3))

In [122]:
b

array([[1, 2, 0],
       [2, 1, 0],
       [2, 1, 1]])

In [136]:
b[:,0]

array([1, 2, 2])

In [143]:
import numpy
game = [
[0,2,1],
[1,1,2],
[1,2,1]]
set_r = ()
set_c = ()
def line_match(game):
    for i in range(3):
        set_r = set(game[i])
        if len(set_r) == 1 and game[i][0] != 0:
            return game[i][0]
        return 0

def diagonal_match(game):
    if game[1][1] != 0:
        if game[1][1] == game[0][0] == game[2][2]: 
            return game[1][1]
        elif game[1][1] == game[0][2] == game[2][0]:
            return game[1][1]
        return 0



In [144]:
if line_match(game) > 0:
    print (str(line_match(game)) + str(" row wins!"))
if line_match(numpy.transpose(game)) > 0:
    print (str(line_match(numpy.transpose(game))) + str(" column wins!"))
if diagonal_match(game) > 0:
    print (str(diagonal_match(game)) + str(" diagonal wins!"))

TypeError: 'int' object is not callable

In [14]:
from flask import Flask
import os

In [18]:
app=Flask(__name__)

In [19]:
@app.route('/hi')
def hello():
    return "hello world!!!!"

@app.route('/mango')
def fruit():
    return "How are you????"


In [23]:
if __name__=='__main__':
    app.debug=True
    app.run()
    

 * Restarting with stat


SystemExit: 1

c:\python27\lib\site-packages\IPython\core\interactiveshell.py:2890: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [1]:
import re

In [79]:
line = "cats are smarter than dogs,cats"

mat = re.match( r'dogs', line)

mats = re.search(r'dogs',line)

matc = re.findall(r'cats',line)

In [81]:
matc

['cats', 'cats']

In [23]:
mats.group(0)

'dogs'

In [83]:
re.sub(r'are',' ',line)

'cats   smarter than dogs,cats'

In [88]:
re.sub('[^aeiou]',' ',line)

' a   a e   a  e    a   o    a  '

In [98]:
s='John, Daniel:123-456'

In [103]:
re.findall(r'(\w+), (\w+):(\S+)',s)

[('John', 'Daniel', '123-456')]

In [91]:
ss= "my name is sharma045454^&%^&%&"
ss

'my name is sharma045454^&%^&%&'

In [95]:
re.sub('[^a-zA-Z ]','',ss)

'my name is sharma'

In [ ]:
import socket              

s = socket.socket()         
host = socket.gethostname() 
port = 12345                
s.bind((host, port))        

s.listen(5)                 
while True:
    c, addr = s.accept()     
    print 'Got connection from', addr
    print c
    c.send('Thank you for connecting')
    c.close()               

In [3]:
import socket               

s = socket.socket()        
host = socket.gethostname() 
port = 12345               

s.connect((host, port))
print s.recv(1024)
s.close  

error: [Errno 10061] No connection could be made because the target machine actively refused it

In [1]:
import socket

In [2]:
socket.gethostname()

'Sharma'

In [17]:
class Employee:
    emp=0
    
    def __init__(self,name,salary):
        self.name=name
        self.salary=salary
        Employee.emp+=1
        
    def display(self):
        print "Name : %s   \nSalary : %d "%(self.name,self.salary)
    
    def count_display(self):
        print Employee.emp

In [25]:
emp1=Employee("apple",5500)
emp2=Employee("ball",46464)

In [26]:
emp1.display()
emp1.count_display()

Name : apple   
Salary : 5500 
5


In [33]:
hasattr(emp1,"name")
getattr(emp1,"name")
delattr(emp1,"salary")

In [35]:
hasattr(emp1,"salary")
setattr(emp1,"age",34)

In [36]:
getattr(emp1,"age")


34

In [40]:
emp1.education="B.E"
del emp1.education

In [41]:
getattr(emp1,"education")

AttributeError: Employee instance has no attribute 'education'

https://jeffknupp.com/blog/2014/06/18/improve-your-python-python-classes-and-object-oriented-programming/

In [86]:
class parent:
    place='a'
    def __init__(self,father,mother):
        self.father = father
        self.mother = mother
    
    def display(self):
        print "parent calling"
        print "Father's Name: %s \nMother's Name: %s"%(self.father,self.mother)
        
    def location(self,loc):
        parent.place=loc
        print "location :",parent.place
        
class child(parent):
    def __init__(self,name):
        self.name = name

    def display_child(self):
        print "child calling"
        print "Child's Name: %s "%self.name

In [87]:
p=parent("john","marry")
c=child("jeff")

In [88]:
p.display()
c.location("c")


parent calling
Father's Name: john 
Mother's Name: marry
location : c


In [54]:
print Employee.__doc__
Employee.__module__

None


'__main__'

In [56]:
Employee.__dict__

{'__doc__': None,
 '__init__': <function __main__.__init__>,
 '__module__': '__main__',
 'count_display': <function __main__.count_display>,
 'display': <function __main__.display>,
 'emp': 5}

In [1]:
import pandas as pd

In [2]:
pd.read_json("./test.json")

ValueError: If using all scalar values, you must pass an index

In [3]:
import json

In [6]:
json.loads("./test.json".read())

AttributeError: 'str' object has no attribute 'read'