In [52]:
a=6
print a+d
d=10


NameError: name 'd' is not defined

In [54]:
print "hello @world"

hello @world


In [6]:
a=500
name='ball'


In [11]:
print a,name,'apple'

500 ball apple


In [14]:
print "hello "+name

hello ball


In [56]:
print "hello "+str(a)
print "hello",a

hello 6


In [57]:
type(a)

int

In [25]:
'''
print 'hi'
print 'hello'
'''

"\nprint 'hi'\nprint 'hello'\n"

In [64]:
#numerical value
num=input("Enter numerical value: ")
#string
nam=raw_input("Enter string: ")

Enter numerical value: 4
Enter string: 10


In [65]:
type(nam)

str

In [67]:
nam*5

'1010101010'

In [68]:
int(nam)+5


15

In [50]:
i=0
while i<3:
    num=input("Enter numerical value: ")
    if num==10:
        print "goodbye"
        break
    elif num==20:
        print "skipping.....,"
        continue
    if num%4==0:
        print "divisible by 4 and even"
    elif num%2==0:
        print 'even'
    else:
        print "odd"
    i+=1

Enter numerical value: 45
odd
Enter numerical value: 12
divisible by 4 and even
Enter numerical value: 18
even


In [34]:
a=input("Enter the side value of the square: ")
r=input("Enter the radius of the circle: ")
area_s=a*a
area_c=3.14*r*r
print "The area of square is",area_s,"sq.cm"
print "The area of circle is",area_c  ,"sq.cm"

Enter the side value of the square: 4
Enter the radius of the circle: 3
The area of square is 16 sq.cm
The area of circle is 28.26 sq.cm


In [69]:
#if-else
num=input(": ")
if num%2==0:
    print "even"
else:
    print "odd"

: 5
odd


In [73]:
#if-elif-else
num=input(": ")
if num%4==0:
    print "divisible by 4"
    if num==8:
        print "number is 8"
elif num%2==0:
    print "even"
else:
    print "odd"

: 8
divisible by 4
number is 8


In [83]:
i=0
while i<len(nam) :
    num=input(": ")
    if num==15:
        break
    elif num==25:
        print "skipping..."
        pass 
    if num%4==0:
        print "divisible by 4"
    elif num%2==0:
        print "even"
    else:
        print "odd"
    opt=raw_input("do you want to continue? y/n")

: 45
odd
do you want to continue? y/ny
: 85
odd
do you want to continue? y/nn


In [85]:
nam='apple'

In [88]:
len(nam)

5

In [89]:
n='5'

In [92]:
int(n*3)+int(n*2)+int(n)

615

In [141]:
name=' Elephant '

In [150]:
name.capitalize()
name.count('e')
name.decode('utf8')
name.endswith('i')
name.startswith('l')
name.find('e')
name.index('p')
name.isdigit()
name.islower()
name.isupper()
name.isspace()
name.lower()
name.upper()
name.lstrip()
name.rstrip()
name.strip()
name.replace('p','f')
name.swapcase()

' eLEPHANT '

In [151]:
sent="elephant is an animal"

In [156]:
sp=sent.split('an')
sp

['eleph', 't is ', ' ', 'imal']

In [157]:
'an'.join(sp)

'elephant is an animal'

1. Palindorme
2. Elephant is an animal -> animal an is Elephant 

In [162]:
sp=sent.split()

In [168]:
" ".join(sp[::-1])

'animal an is elephant'

1. Rock beats scissors
2. Scissors beats paper
3. Paper beats rock

In [1]:
import random as r

In [2]:
comp=r.randint(0,20)

In [ ]:
while 1:
    num=raw_input("Enter your guess : ")
    if num=='q' or num=="quit":
        break
    int(num)

In [3]:
#list
l=[]
L=[1,'a','apple',2,'b','ball',3,'c','cat']

In [19]:
L.reverse()

In [31]:
L.append(2)

In [36]:
L.count()

TypeError: count() takes exactly one argument (0 given)

In [28]:
l.append("orange")

In [34]:
L.extend('orange')

In [46]:
len(L)

11

In [47]:
L

[1, 'a', 'apple', 2, 'b', 'ball', 3, 'c', 'cat', 'dog', 2]

In [48]:
L[3]=8

In [49]:
L

[1, 'a', 'apple', 8, 'b', 'ball', 3, 'c', 'cat', 'dog', 2]

In [50]:
L.index(8)

3

In [56]:
del L[4]

SyntaxError: can't delete function call (<ipython-input-56-91ceb31a7be2>, line 1)

In [54]:
L.insert(4,"elephant")

In [57]:
L.pop()

2

In [67]:
L.remove(3)

In [65]:
L.append(3)

In [69]:
L.sort()

In [70]:
L

[1, 3, 8, 'a', 'apple', 'ball', 'c', 'cat', 'dog', 'elephant']

In [72]:
#tuple
days=('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')

In [84]:
#dictionary
d={'a':'apple','b':'ball','c':'cat',1:'orange','d':4,'m':'mango'}

In [85]:
d.keys()

['a', 1, 'c', 'b', 'd', 'm']

In [86]:
d.values()

['apple', 'orange', 'cat', 'ball', 4, 'mango']

In [90]:
d["s"]="sun"

In [95]:
print d.items()

[('a', 'apple'), (1, 'orange'), ('c', 'cat'), ('b', 'ball'), ('d', 4), ('m', 'mango'), ('s', 'sun')]


In [96]:
d

{1: 'orange',
 'a': 'apple',
 'b': 'ball',
 'c': 'cat',
 'd': 4,
 'm': 'mango',
 's': 'sun'}

In [97]:
L

[1, 3, 8, 'a', 'apple', 'ball', 'c', 'cat', 'dog', 'elephant']

In [98]:
days

('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')

In [116]:
for i in d:
    print i

a
1
c
b
d
m
s


In [106]:
name='apple'

In [107]:
len(name)

5

##task##
1. Take two list and print the common number between two list without duplicates
2. Take one numerical list of length atleast 15 and create a new list with number less than 10 of list A.


In [117]:
a=['a','b','c','a']
b=['a','c','e','n','a']

In [120]:
d=[]
for i in b:
     if i in a:
            d.append(i)

In [122]:
set(d)

{'a', 'c'}

In [130]:
list(set(a)&set(b))

['a', 'c']

In [124]:
s=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,15,7,4]

In [125]:
e=[]
for i in s if i<=10:
        e.append(i)
        

In [12]:
e

NameError: name 'e' is not defined

In [128]:
f=[i for i in s if i<=10]

In [129]:
f

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 7, 4]

In [132]:
import random as r

In [136]:
r.randint(0,10)

2

In [137]:
from math import *

In [138]:
factorial(5)

120

In [139]:
sin(90)

0.8939966636005579

In [140]:
from math import sin,tanh,factorial

In [141]:
r.choice()
r.sample()
r.randint()
r.randrange()

TypeError: choice() takes exactly 2 arguments (1 given)

In [142]:
s="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789`~!@#$%^&*()_+=-|\{}[]:/?>,<"

In [149]:
''.join(r.sample(s,8))

'5KpNUC*e'

In [162]:
#error-handling
try:
    print x
except:
    print "There is an error!!!"


There is an error!!!


In [192]:
#functions
def addition(b,a=25):
    return a+b,a*b

In [190]:
a=input('a: ')
b=input('b: ')
c,m=addition(a)

a: 10
b: 25


TypeError: addition() takes exactly 2 arguments (1 given)

In [188]:
c

20

In [186]:
m

375

In [177]:
s

'sum'

In [17]:
f=open("tango.txt","a+")
f.write("\nhi,how are you?")
f.write("\ni am fine")
f.close()

In [24]:
f1=open('tango.txt',mode='r',encoding='utf8')

In [19]:
f1.read()

'hi,how are you?\ni am finehi,how are you?\ni am finehi,how are you?\ni am fine\nhi,how are you?\ni am fine'

In [6]:
f1.readable()

True

In [23]:
f1.readline()

'i am finehi,how are you?\n'

In [25]:
f1.readlines()

['hi,how are you?\n',
 'i am finehi,how are you?\n',
 'i am finehi,how are you?\n',
 'i am fine\n',
 'hi,how are you?\n',
 'i am fine']

In [1]:
import numpy as np

In [2]:
import numpy.linalg as la

In [3]:
A=np.asmatrix([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
A[1]

matrix([[4, 5, 6]])

In [7]:
A[:,1]

matrix([[2],
        [5],
        [8]])

In [9]:
A.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
print (np.ravel(A))

[1 2 3 4 5 6 7 8 9]


In [18]:
B=[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
np.reshape(B,[3,3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
la.det(A)

0.0

In [22]:
C=np.asmatrix([[2,1,1],[1,1,1],[1,-1,2]])

In [23]:
C

matrix([[ 2,  1,  1],
        [ 1,  1,  1],
        [ 1, -1,  2]])

In [26]:
la.det(C)

2.9999999999999996

In [28]:
print(C.I)

[[ 1.         -1.          0.        ]
 [-0.33333333  1.         -0.33333333]
 [-0.66666667  1.          0.33333333]]


In [32]:
float(22/7)

3.142857142857143

In [36]:
A.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [37]:
C

matrix([[ 2,  1,  1],
        [ 1,  1,  1],
        [ 1, -1,  2]])

In [42]:
D=np.asmatrix([[5],[4],[1]])

In [43]:
D

matrix([[5],
        [4],
        [1]])

In [41]:
la.solve(C,D.T)

matrix([[1.],
        [2.],
        [1.]])

In [44]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
np.zeros([4,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.full([3,3],7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [52]:
C

matrix([[ 2,  1,  1],
        [ 1,  1,  1],
        [ 1, -1,  2]])

In [54]:
la.eig(C)[1]

matrix([[-8.01783726e-01, -7.07106781e-01,  7.07106781e-01],
        [-5.34522484e-01, -1.32382025e-08, -1.32382025e-08],
        [-2.67261242e-01,  7.07106781e-01, -7.07106781e-01]])

In [55]:
la.eig(C)

(array([3.        , 1.00000002, 0.99999998]),
 matrix([[-8.01783726e-01, -7.07106781e-01,  7.07106781e-01],
         [-5.34522484e-01, -1.32382025e-08, -1.32382025e-08],
         [-2.67261242e-01,  7.07106781e-01, -7.07106781e-01]]))

In [56]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [57]:
C

matrix([[ 2,  1,  1],
        [ 1,  1,  1],
        [ 1, -1,  2]])

In [58]:
A*C

matrix([[ 7,  0,  9],
        [19,  3, 21],
        [31,  6, 33]])

In [59]:
C*A

matrix([[13, 17, 21],
        [12, 15, 18],
        [11, 13, 15]])

In [60]:
A+C

matrix([[ 3,  3,  4],
        [ 5,  6,  7],
        [ 8,  7, 11]])

In [61]:
4*C

matrix([[ 8,  4,  4],
        [ 4,  4,  4],
        [ 4, -4,  8]])

In [62]:
D

matrix([[5],
        [4],
        [1]])

In [63]:
la.norm(D)

6.48074069840786

In [65]:
np.sqrt(25+16+1)

6.48074069840786

In [71]:
F= np.matrix(np.random.random((3,3)))

In [72]:
F

matrix([[0.56080439, 0.40470409, 0.9258669 ],
        [0.07985019, 0.13827478, 0.72897899],
        [0.76391931, 0.44739706, 0.14144427]])

In [73]:
la.svd(C)

(matrix([[-0.67937901,  0.45611003,  0.5748111 ],
         [-0.46675103,  0.3358339 , -0.81814367],
         [-0.56620459, -0.82412331, -0.01526867]]),
 array([3.35385579, 1.87740375, 0.47645204]),
 matrix([[-0.71312358, -0.17291305, -0.67937901],
         [ 0.22580687,  0.86079899, -0.45611003],
         [ 0.66367614, -0.47867126, -0.5748111 ]]))